### ISSUE TITLE
Handling dynamic values for vBusyLabel and the button text

### ISSUE THREAD

**Issue by hthabet** [LukaszWatroba/v-button#1]
Hi @LukaszWatroba, 
I really like your directive. However it has a limit when we use dynamic values for the **_vBusyLabel_** attribute and **_idleLabelHtml_**. For instance, I use angluar-translate and my code using v-button directive will look like this : 

```
<button class="btn" v-busy="auth.isBusy" v-busy-label="{{'auth.states.signin.signing_in' | translate}}"><span translate>auth.states.signin.signin_button</span></button>
```

In this case, when I change the translation locale, **_busyLabelHtml_** is never updated.
Also, when the button is done being busy, **_idleLabelHtml_** returns what was in labelElement.html() (based on code below) which is in this case equal to **_auth.states.signin.signin_button_** and not the wanted translated text.

```

labelElement = angular.element(tElement.find('span'));

...

idleLabelHtml = labelElement.html(),
```

I already wrote a fix and I will be glad to submit a PR :)

**Comment by LukaszWatroba** [comment]
Thanks @hthabet.
Go ahead, pull requests are always welcome  :)

**Comment by hthabet** [comment]
@LukaszWatroba done!

**Comment by LukaszWatroba** [comment]
Merged. Thank you @hthabet
